---

- name: Install python-psycopg2
  apt: name=python-psycopg2

- include: local_database.yml
  when: postgres.server.installed_locally

- include: rds.yml
  when: not postgres.server.installed_locally
