
- name: Install redis
  apt: pkg=redis-server state=latest

# TODO: is this ok like this?
- name: Configure redis
  lineinfile: dest=/etc/redis/redis.conf regexp="^bind " state=absent
  register: configure_redis

- name: Restart redis
  service: name=redis-server state=restarted
  when: configure_redis is changed

- name: Ensure redis is started
  service: name=redis-server state=started
