---

- name: Initialize CKAN database
  command: ./bin/ckan "--config={{ ckan_ini }}" db init chdir={{ virtualenv }}
  ignore_errors: True

- name: Upgrade CKAN database
  command: ./bin/ckan "--config={{ ckan_ini }}" db upgrade chdir={{ virtualenv }}
  ignore_errors: True

- name: Create initial CKAN users
  command: ./bin/ckan  "--config={{ ckan_ini }}" user add "{{ item.value.username }}" "password={{ item.value.password }}" "email={{ item.value.email }}" chdir={{ virtualenv }}
  ignore_errors: True
  with_dict: "{{ ckan_users }}"

- name: Set CKAN sysadmins
  command: ./bin/ckan "--config={{ ckan_ini }}" sysadmin add {{ item }} chdir={{ virtualenv }}
  ignore_errors: True
  with_items: "{{ ckan_admins }}"

#- name: Initialize Harvest database
#  command: ./bin/paster --plugin=ckanext-harvest harvester initdb "--config={{ ckan_ini }}" chdir={{ virtualenv }}
#  when: "'ckanext-harvest' in ckan_extensions"
  
- name: Initialize archiver database
  command: ./bin/ckan "--config={{ ckan_ini }}" archiver init  chdir={{ virtualenv }}

# This can be removed after run in all environments
#- name: Migrate archiver database
#  command: ./bin/paster --plugin=ckanext-archiver archiver migrate "--config={{ ckan_ini }}" chdir={{ virtualenv }}

- name: Initialize report database
  command: ./bin/ckan "--config={{ ckan_ini }}" report initdb  chdir={{ virtualenv }}

- name: Initialize QA database
  command: ./bin/ckan "--config={{ ckan_ini }}" qa init  chdir={{ virtualenv }}

#- name: Initialize Rating database
#  command: ./bin/paster --plugin=ckanext-rating rating init "--config={{ ckan_ini }}" chdir={{ virtualenv }}

- name: Initialize Reminder database
  command: ./bin/ckan "--config={{ ckan_ini }}" reminder init-db chdir={{ virtualenv }}

- name: Initialize ckanext-matomo database
  command: ./bin/ckan "--config={{ ckan_ini }}" matomo init_db  chdir={{ virtualenv }}
  when: "'ckanext-matomo' in ckan_extensions"

- name: Upgrade ckanext-matomo database
  command: ./bin/ckan "--config={{ ckan_ini }}" db upgrade -p matomo  chdir={{ virtualenv }}
  when: "'ckanext-matomo' in ckan_extensions"


#- name: Initialize ckanext-ga-report database
#  command: ./bin/paster --plugin=ckanext-ga-report initdb "--config={{ ckan_ini }}" chdir={{ virtualenv }}
#  when: "'ckanext-ga-report' in ckan_extensions"

#- name: Initialize ckanext-cloudstorage database
#  command: ./bin/paster --plugin=ckanext-cloudstorage cloudstorage initdb "--config={{ ckan_ini }}" chdir={{ virtualenv }}
#  when: AWS.enabled