---
env:
  browser: true
  jquery: true
  commonjs: true
extends: eslint:recommended
rules:
  indent:
  - error
  - 2
  - SwitchCase: 1
  no-trailing-spaces:
  - error
  - skipBlankLines: false
  linebreak-style:
  - error
  - unix
  quotes:
  - error
  - single
  semi:
  - error
  - always
  console:
  - error
  no-alert:
  - error
  block-scoped-var:
  - warn
  no-redeclare:
  - warn
  no-param-reassign:
  - warn
  no-self-compare:
  - warn
  no-else-return:
  - warn
  consistent-return:
  - warn
  array-callback-return:
  - warn
  curly:
  - warn
  eqeqeq:
  - warn
  yoda:
  - warn
  no-multi-spaces:
  - warn
  radix:
  - warn
  - always
  no-with:
  - error
  no-useless-call:
  - warn
  no-useless-concat:
  - warn
  no-undefined:
  - warn
  