---

- name: Add openjdk8 PPA
  apt_repository: repo="ppa:openjdk-r/ppa"
  register: java8_repo_added

- name: Install Java 8
  apt: name=openjdk-8-jdk update_cache=yes
  when: java8_repo_added|changed
