---

public_facing_hostname: build
internal_hostname: build
ckan_site_name: Dataportaali
ckan_featured_orgs:

postgres:
  server:
    installed_locally: false
    host: localhost
    admin_user: ckan_admin
    admin_password: "{{ secret.database_ckan_admin_password }}"
    trusted_ip_range: 127.0.0.1/32
  users:
    ckan:
      username: ckan_default
      password: "{{ secret.database_ckan_password }}"
    ckan_datastore: 
      username: datastore_default
      password: "{{ secret.database_ckan_datastore_password }}"
  databases: 
    ckan:
      name: ckan_default
      owner: ckan_default
    ckan_datastore:
      name: datastore_default
      owner: ckan_default

nginx:
  use_ssl_certificate: true
  use_selfsigned_certificate: true
  fqdn_common_part: dataportaali.com
  alternative_hostnames: www.{{ public_facing_hostname }}

solr:
  host: 127.0.0.1
  port: 8983
  listen_address: 127.0.0.1

redis:
  host: 127.0.0.1
  port: 6379

ckan_users:
  admin:
    username: admin
    password: "{{ secret.ckan_admin_password }}"
    email: admin@localhost
  harvest:
    username: harvest
    password: "{{ secret.ckan_harvest_password }}"
    email: harvest@localhost
  test:
    username: test
    password: "{{ secret.ckan_test_password }}"
    email: testuser@localhost

ckan_admins:
  - "{{ ckan_users.admin.username }}"
  - "{{ ckan_users.harvest.username }}"

email_domain: "{{ public_facing_hostname }}"
email:
  smtp_server: localhost
  from: no-reply@{{ email_domain }}
  error_recipient: admin@localhost
  error_from: error@{{ email_domain }}
  contact: not-implemented@localhost

robots_allowed: false

debug_enabled: false

AWS:
  enabled: false
  use_iam_role: false
  access_key: somekey
  secret_access_key: somesecret
  ckan_s3_bucket: sixodp-testi-ampari
  region: S3_EU_WEST
