---

cache_path: /root/.cache

public_facing_hostname: build
internal_hostname: build
cms_site_url: localhost
ckan_internal_host: 127.0.0.1:8080
ckan_internal_url: "{{ 'http://' + ckan_internal_host }}"
ckan_site_name: Dataportaali
ckan_featured_orgs:
automatic_updates: false
automatic_updates_recipient: root@localhost

postgres:
  server:
    installed_locally: true
    host: 127.0.0.1
    admin_user: ckan_admin
    admin_password: "{{ secret.database_ckan_root_password }}"
    trusted_ip_range: 127.0.0.1/32
  users:
    ckan:
      username: ckan_default
      password: "{{ secret.database_ckan_password }}"
    ckan_datastore: 
      username: datastore_default
      password: "{{ secret.database_ckan_datastore_password }}"
  databases: 
    ckan:
      name: ckan_default
      owner: ckan_default
    ckan_datastore:
      name: datastore_default
      owner: ckan_default

mysql:
  server:
    installed_locally: true
    host: localhost
    admin_user: root
    admin_password: "{{ secret.database_wordpress_root_password }}"
  users:
    wordpress:
          username: wordpress
          password: "{{ secret.database_wordpress_password}}"
  databases:
    wordpress:
      name: wordpress
      owner: wordpress

nginx:
  use_ssl_certificate: true
  use_selfsigned_certificate: true
  fqdn_common_part: dataportaali.com
  alternative_hostnames: www.{{ public_facing_hostname }}

solr:
  host: 127.0.0.1
  port: 8983
  listen_address: 127.0.0.1

redis:
  host: 127.0.0.1
  port: 6379

ckan_users:
  admin:
    username: admin
    password: "{{ secret.ckan_admin_password }}"
    email: admin@localhost
  harvest:
    username: harvest
    password: "{{ secret.ckan_harvest_password }}"
    email: harvest@localhost
  test:
    username: test
    password: "{{ secret.ckan_test_password }}"
    email: testuser@localhost

ckan_admins:
  - "{{ ckan_users.admin.username }}"
  - "{{ ckan_users.harvest.username }}"

wordpress_users:
  admin:
    username: admin
    password: "{{ secret.wordpress_admin_password }}"
    email: admin@localhost.localdomain

ckan_extensions:
  - ckanext-sixodp_routes
  - ckanext-sixodp_scheming
  - ckanext-sixodp_ui
  - ckanext-sixodp_showcase
  - ckanext-scheming
  - ckanext-showcase
  - ckanext-fluent
  #- ckanext-harvest
  - ckanext-cloudstorage
  - ckanext-report
  - ckanext-ga-report
  - ckanext-qa
  - ckanext-archiver
  - ckanext-hierarchy
  - ckanext-disqus
  - ckanext-reminder
  - ckanext-rating
  - ckanext-editor
  - ckanext-collection
  - ckanext-datasetcopy
  #- ckanext-spatial
  - ckanext-datasubmitter
  - ckanext-statistics
  #- ckanext-sixodp_harvester
  - ckanext-sixodp_showcasesubmit

# List of enabled CKAN extensions in load order. Order matters, when templates call super()
enabled_ckan_extensions:
    - disqus
    - datapusher
    - text_view
    - image_view
    - recline_view
    - recline_graph_view
    - recline_grid_view
    - recline_map_view
    - sixodp_showcase
    - sixodp_ui
    - datastore
    - datasetcopy
    - sixodp_scheming
    - scheming_datasets
    - scheming_groups
    - fluent
    - report
    - ga-report
    - publisher_activity_report
    - rating
    - sixodp_routes
    - sixodp_feed
    - qa
    - archiver
    - hierarchy_display
    - hierarchy_form
    - reminder
    - editor
    - collection
    #- spatial_metadata
    #- spatial_query
    - datasubmitter
    #- harvest
    - statistics
    #- csw_harvester
    #- sixodp_harvester
    - sixodp_showcasesubmit

enabled_ckan_aws_extensions: cloudstorage

ckan_site_id: "default"

email_domain: "{{ public_facing_hostname }}"
email:
  smtp_server: localhost
  from: no-reply@{{ email_domain }}
  error_recipient: admin@localhost
  error_from: error@{{ email_domain }}
  contact: not-implemented@localhost

robots_allowed: false

debug_enabled: false

AWS:
  enabled: false
  use_iam_role: false
  access_key: somekey
  secret_access_key: somesecret
  ckan_s3_bucket: sixodp-testi-ampari
  region: S3_EU_WEST

recaptcha_sitekey: somesitekey

disqus_public_key: "{{ secret.disqus_public_key }}"
disqus_secret_key: "{{ secret.disqus_secret_key }}"
disqus_short_name: "{{ secret.disqus_short_name }}"