---

public_facing_hostname: liityntakatalogi.suomi.fi
internal_hostname: catalog-prod
ckan_site_name: Liityntäkatalogi

analytics_server_public_facing_hostname: kapastats01.csc.fi
analytics_site_id: 2

database_ckan:
  host: 127.0.0.1
  port: 5432
  allowed_ip_range: 127.0.0.1/32
  name: ckan_default
  username: ckan_default
  password: "{{ secret.database_ckan_password }}"

nginx:
  alternative_hostnames: api.suomi.fi apikatalogi.suomi.fi katalogiprod01.csc.fi

solr:
  host: 127.0.0.1
  port: 8983
  listen_address: 127.0.0.1

redis:
  host: 127.0.0.1
  port: 6379

ckan_users:
  admin:
    username: admin
    password: "{{ secret.ckan_admin_password }}"
    email: admin@localhost
  harvest:
    username: harvest
    password: "{{ secret.ckan_harvest_password }}"
    email: harvest@localhost
  test:
    username: test
    password: "{{ secret.ckan_test_password }}"
    email: testuser@localhost

ckan_admins:
  - "{{ ckan_users.admin.username }}"
  - "{{ ckan_users.harvest.username }}"

email_domain: "{{ public_facing_hostname }}"
email:
  smtp_server: localhost
  from: no-reply@{{ email_domain }}
  error_recipient: admin@localhost
  error_from: error@{{ email_domain }}
  contact: kapa-asiakaspalvelu@vrk.fi

xroad:
  securityserver:
    host: "gdev-ss2.palveluvayla.com"
    alias: "gdev-ss2"
    port: 443
