---

public_facing_hostname: demo.dataportaali.com
internal_hostname: sixodp-qa
ckan_site_name: Dataportaali
ckan_featured_orgs:

postgresql_users:
  ckan:
    username: ckan_default
    password: "{{ secret.database_ckan_password }}"
  ckan_datastore: 
    username: datastore_default
    password: "{{ secret.database_ckan_datastore_password }}"

postgresql_databases: 
  ckan:
    host: 127.0.0.1
    port: 5432
    allowed_ip_range: 127.0.0.1/32
    name: ckan_default
    encoding: UTT-8
    collate: en_US.UTF-8
    ctype: en_US.UTF-8
    template: template0
    owner: ckan_default
  ckan_datastore:
    host: 127.0.0.1
    port: 5432
    allowed_ip_range: 127.0.0.1/32
    name: datastore_default
    encoding: UTF-8
    collate: en_US.UTF-8
    ctype: en_US.UTF-8
    template: template0
    owner: ckan_default

nginx:
  use_ssl_certificate: true
  use_selfsigned_certificate: false
  fqdn_common_part: dataportaali.com
  alternative_hostnames: www.{{ public_facing_hostname }}

solr:
  host: 127.0.0.1
  port: 8983
  listen_address: 127.0.0.1

redis:
  host: 127.0.0.1
  port: 6379

ckan_users:
  admin:
    username: admin
    password: "{{ secret.ckan_admin_password }}"
    email: admin@localhost
  harvest:
    username: harvest
    password: "{{ secret.ckan_harvest_password }}"
    email: harvest@localhost
  test:
    username: test
    password: "{{ secret.ckan_test_password }}"
    email: testuser@localhost

ckan_admins:
  - "{{ ckan_users.admin.username }}"
  - "{{ ckan_users.harvest.username }}"

email_domain: "{{ public_facing_hostname }}"
email:
  smtp_server: localhost
  from: no-reply@{{ email_domain }}
  error_recipient: admin@localhost
  error_from: error@{{ email_domain }}
  contact: not-implemented@localhost

robots_allowed: false

debug_enabled: false

AWS:
  enabled: true
  use_iam_role: true
  check_access: true
  ckan_s3_bucket: sixodp-testi-ampari
  filesystem_download_fallback: false