---
vagrant: true

public_facing_hostname: 10.106.10.10
internal_hostname: sixodp-vagrant
ckan_site_name: Dataportaali
ckan_featured_orgs:

postgresql_users:
  ckan:
    username: ckan_default
    password: "{{ secret.database_ckan_password }}"
  ckan_datastore: 
    username: datastore_default
    password: "{{ secret.database_ckan_datastore_password }}"

postgresql_databases: 
  ckan:
    host: 127.0.0.1
    port: 5432
    allowed_ip_range: 10.0.0.0/8
    name: ckan_default
    encoding: UTF-8
    collate: en_US.UTF-8
    ctype: en_US.UTF-8
    template: template0
    owner: ckan_default
  ckan_datastore:
    host: 127.0.0.1
    port: 5432
    allowed_ip_range: 10.0.0.0/8
    name: datastore_default
    encoding: UTF-8
    collate: en_US.UTF-8
    ctype: en_US.UTF-8
    template: template0
    owner: ckan_default

nginx:
  use_ssl_certificate: true
  use_selfsigned_certificate: true
  fqdn_common_part: goforecrew.com
  alternative_hostnames: www.{{ public_facing_hostname }}

solr:
  host: 127.0.0.1
  port: 8983
  listen_address: 0.0.0.0

redis:
  host: 127.0.0.1
  port: 6379

ckan_users:
  admin:
    username: admin
    password: "{{ secret.ckan_admin_password }}"
    email: vagrant@localhost
  harvest:
    username: harvest
    password: "{{ secret.ckan_harvest_password }}"
    email: harvest@localhost
  test:
    username: test
    password: "{{ secret.ckan_test_password }}"
    email: testuser@localhost

ckan_admins:
  - "{{ ckan_users.admin.username }}"
  - "{{ ckan_users.harvest.username }}"

email_domain: vagrant
email:
  smtp_server: localhost
  from: no-reply@{{ email_domain }}
  error_recipient: vagrant@localhost
  error_from: error@{{ email_domain }}
  contact: vagrant@localhost

robots_allowed: true

debug_enabled: true

AWS:
  enabled: false
  use_iam_role: false
  access_key: somekey
  secret_access_key: somesecret
  ckan_s3_bucket: sixodp-testi-ampari
  S3_EU_WEST
