---

public_facing_hostname: 10.100.10.10
internal_hostname: catalog-vagrant
ckan_site_name: Liityntäkatalogi

database_ckan:
  host: 127.0.0.1
  port: 5432
  allowed_ip_range: 10.0.0.0/8
  name: ckan_default
  username: ckan_default
  password: "{{ secret.database_ckan_password }}"

nginx:
  alternative_hostnames: catalog-alternative

solr:
  host: 127.0.0.1
  port: 8983
  listen_address: 0.0.0.0

redis:
  host: 127.0.0.1
  port: 6379

ckan_users:
  admin:
    username: admin
    password: "{{ secret.ckan_admin_password }}"
    email: vagrant@localhost
  harvest:
    username: harvest
    password: "{{ secret.ckan_harvest_password }}"
    email: harvest@localhost
  test:
    username: test
    password: "{{ secret.ckan_test_password }}"
    email: testuser@localhost

ckan_admins:
  - "{{ ckan_users.admin.username }}"
  - "{{ ckan_users.harvest.username }}"

email_domain: vagrant
email:
  smtp_server: localhost
  from: no-reply@{{ email_domain }}
  error_recipient: vagrant@localhost
  error_from: error@{{ email_domain }}
  contact: vagrant@localhost

xroad:
  securityserver: "https://gdev-ss2.palveluvayla.com"
  keyAlias: qa-harvester
