---

- name: Ensure temp directory for extensions
  file: path="{{ ckanext_sync_path }}" state=directory

- name: Synchronize extension sources
  synchronize: src=../ckanext/{{ ckanext }} dest="{{ ckanext_sync_path }}"/

# TODO: This is designed for Vagrant
- name: Link extension sources
  command: "{{ virtualenv }}/bin/python setup.py develop chdir="{{ ckanext_sync_path }}/{{ ckanext }}"
