---

- name: Enable supervisor
  service: name=supervisor enabled=yes state=started

#TODO: fix supervisor for ubuntu xenial https://bugs.launchpad.net/ubuntu/+source/supervisor/+bug/1594740
- name: Create log path for supervisor
  file: path={{ supervisor_log_path }} state=directory

- name: Copy supervisor configuration
  template: src="supervisor.conf.j2" dest="/etc/supervisor/conf.d/catalog.conf" mode=0644 owner=root group=root
  register: supervisor_configuration
  notify:
  # - Restart Gather
  # - Restart Fetch

- name: Reread supervisor
  command: supervisorctl reread
  when: supervisor_configuration is changed

- name: Ensure supervisor services
  command: supervisorctl add {{ item }}
  when: supervisor_configuration is changed
  with_items: "{{ supervisor_services }}"

- name: Ensure supervisor services are restarted
  supervisorctl: name={{ item }} state=restarted
  when: supervisor_configuration is changed
  with_items: "{{ supervisor_services }}"

- name: Ensure supervisor services are started
  supervisorctl: name={{ item }} state=started
  with_items: "{{ supervisor_services }}"
