---

- name: Enable supervisor
  service: name=supervisor enabled=yes state=started

#TODO: fix supervisor for ubuntu xenial https://bugs.launchpad.net/ubuntu/+source/supervisor/+bug/1594740
- name: Create log path for supervisor
  file: path={{ supervisor_log_path }} state=directory

- name: Copy supervisor configuration
  template: src="supervisor.conf.j2" dest="/etc/supervisor/conf.d/catalog.conf" mode=0644 owner=root group=root
  register: supervisor_configuration
  notify:
  # - Restart Gather
  # - Restart Fetch

- name: Ensure ckan services in supervisor
  supervisorctl:
    name: "{{ item }}"
    state: present
  with_items:
    - "ckan-uwsgi:"
  when: background_server == False

- name: Ensure ckan background services in supervisor
  supervisorctl:
    name: "{{ item }}"
    state: present
  with_items:
    - "ckan-worker-bulk"
    - "ckan-worker-priority"
  when: background_server == True


- name: Ensure ckan services are started
  supervisorctl:
    name: all
    state: started
