---

- name: Create log path for supervisor
  file: path={{ supervisor_log_path }} state=directory

- name: Ensure CKAN common packages
  apt: pkg={{ item }} state=latest
  with_items:
    - supervisor

- name: Copy supervisor configuration
  template: src="supervisor.conf.j2" dest="/etc/supervisor/conf.d/catalog.conf" mode=0644 owner=root group=root
  register: supervisor_configuration
  notify:
  - Restart Gather
  - Restart Fetch

- name: Reread supervisor
  shell: supervisorctl reread
  when: supervisor_configuration|changed

- name: Ensure supervisor services
  shell: supervisorctl add {{ item }}
  when: supervisor_configuration|changed
  with_flattened:
    - supervisor_services

- name: Ensure supervisor services are restarted
  supervisorctl: name={{ item }} state=restarted
  when: supervisor_configuration|changed
  with_flattened:
    - supervisor_services

- name: Ensure supervisor services are started
  supervisorctl: name={{ item }} state=started
  with_flattened:
    - supervisor_services

