---

- name: Restart Gather
  supervisorctl: name=ckan_gather_consumer state=restarted

- name: Restart Fetch
  supervisorctl: name=ckan_fetch_consumer state=restarted

- name: Restart Celery (default queue)
  supervisorctl: name=celery_celery state=restarted

- name: Restart Celery (bulk queue)
  supervisorctl: name=celery_bulk state=restarted

- name: Restart Celery (priority queue)
  supervisorctl: name=celery_priority state=restarted

- name: Restart Celerybeat
  supervisorctl: name=celerybeat state=restarted
