---

- name: Install postfix
  apt: pkg=postfix state=latest
  tags:
  - postfix
  - non-local

- name: Setup postfix
  template: src="main.cf.j2" dest="/etc/postfix/main.cf" owner=root group=root mode="0644"
  tags:
  - postfix
  - non-local

- name: Restart Postfix
  service: name=postfix state=restarted
