---

- name: Install postfix
  apt: pkg=postfix state=latest
  tags:
  - postfix
  - non-local

- name: Setup postfix
  template: src="main.cf.j2" dest="/etc/postfix/main.cf" owner=root group=root mode="0644"
  notify: Restart Postfix
  tags:
  - postfix
  - non-local
