---

- name: Install database backup tools
  action: apt pkg="{{ item }}" state="present"
  with_items:
  - autopostgresqlbackup
  - mailutils

- name: Setup pre backup script
  copy: src=pre-backup.bash dest="{{ scripts_path }}/pre-backup.bash" mode=0755 owner=root group=root

- name: Setup database backup
  template: src=autopostgresqlbackup.j2 dest=/etc/default/autopostgresqlbackup mode=0755 owner=root group=root

- name: Run backup now
  command: /usr/sbin/autopostgresqlbackup

- name: Copy backup cleanup
  template: src=clean_backups.sh.j2 dest="/etc/cron.daily/ytp_clean_backups" mode=0755 owner=root group=root
