---

- name: Ensure spatial requirements
  apt: pkg="{{ item }}" state=present
  register: postgis_installed
  with_items:
    - postgresql-9.3-postgis-2.1
  tags:
  - packages
  - spatial

- name: Spatial table references
  command: sudo -u postgres psql -d "{{ database_ckan.name }}" -f "{{ item }}"
  when: postgis_installed|changed
  with_items:
    - "/usr/share/postgresql/9.3/contrib/postgis-2.1/postgis.sql"
    - "/usr/share/postgresql/9.3/contrib/postgis-2.1/spatial_ref_sys.sql"
  tags:
  - spatial

- name: Spatial table rights
  command: sudo -u postgres psql -d "{{ database_ckan.username }}" -c "{{ item }}"
  when: postgis_installed|changed
  with_items:
    - "ALTER TABLE spatial_ref_sys OWNER TO {{ database_ckan.username }};"
    - "ALTER TABLE geometry_columns OWNER TO {{ database_ckan.username }};"
  tags:
  - spatial
