---

- name: Restart ckan
  command: echo "Restarting ckan"
  notify: Restart ckan

- name: Flush handlers
  meta: flush_handlers

# Fixes permissions of generated files
- name: Start CKAN
  uri:
    url: "http://127.0.0.1:8080"