---

- name: Ensure temp directory for extensions
  file: path={{ ckanext_sync_path }} state=directory

- block:
  - name: Install npm dependencies
    npm:
      path: "{{ playbook_dir }}/.."

  - name: Build CSS
    command: npm run build
    args:
      chdir: "{{ playbook_dir }}/.."

  when: deployment_environment_id != "vagrant"

- include: extension.yml
  with_items: "{{ ckan_extensions }}"

- block:
  - name: Copy googleanalytics secrets to vagrant
    copy: src="/{{playbook_dir}}/../sixodp-secrets/google_analytics_credentials.json" dest="{{ cache_path }}/google_analytics_credentials.json"

  - name: Set ckanext-googleanalytics credentials
    command: ./bin/paster --plugin=ckanext-googleanalytics loadanalytics {{ cache_path }}/google_analytics_credentials.json "--config={{ ckan_ini }}" chdir={{ virtualenv }}

  when: deployment_environment_id == "vagrant"

- name: Restart Apache
  service: name=apache2 state=restarted
