---

# Web modules

- name: Clear module cache
  file: path="{{ cache_path }}/{{ item }}" state=absent
  with_flattened:
    - modules
  when: clear_module_cache
  tags:
  - common
  - clear-cache

- name: Clear module tar cache
  file: path="{{ cache_path }}/{{ item }}.tar" state=absent
  with_flattened:
    - modules
  when: clear_module_cache
  tags:
  - common
  - clear-cache

- name: Package modules
  local_action: command tar -c --exclude=.git --exclude-from={{ item }}/.gitignore -f {{ item }}.tar {{ item }} chdir="{{ modules_path }}"
  sudo: false
  with_flattened:
    - modules
  tags:
  - common
  - ckan
  - resources
  - modules
  - translations

- name: Copy modules
  copy: src="{{ modules_path }}/{{ item }}.tar" dest="{{ cache_path }}"
  register: modules_copy
  with_flattened:
    - modules
  tags:
  - common
  - ckan
  - resources
  - modules
  - translations

- name: Extract modules
  shell: rm -Rf "{{ item }}" && tar xf "{{ item }}.tar" chdir="{{ cache_path }}"
  when: modules_copy|changed
  with_flattened:
    - modules
  tags:
  - common
  - ckan
  - resources
  - modules
  - translations
