---

- name: Install gulp
  npm: name=gulp global=yes
  when: modules_copy|changed
  tags:
  - resources

- name: Install resource dependencies
  npm: path={{cache_path}}/ytp-assets-common state=present
  when: modules_copy|changed
  tags:
  - resources

- name: Generate resources
  command: "gulp chdir={{cache_path}}/ytp-assets-common"
  when: modules_copy|changed
  tags:
  - resources

- name: Copy resources
  shell: cp -R {{ cache_path }}/ytp-assets-common/resources /var/www/resources
  when: modules_copy|changed
  tags:
  - resources
