---

- name: Configure SSH
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: "0644"
    owner: root
    group: root
    backup: yes
    validate: '/usr/sbin/sshd -T -f %s'

- name: Restart SSH
  service: name=ssh state=restarted
