---

xroad_tunnel:
  name: xroad-tunnel
  user: xroad-tunnel
  configuration_path: /opt/xroad-tunnel/ssh-config
  key_path: /opt/xroad-tunnel/kapa_rsa
  local_port: '12765'
  tunneling_host: dev-is.palveluvayla.com
  destination_host: "{{ xroad.securityserver.host }}"
  remote_tunnel_user: ian
  remote_port: '443'
