---
xroad_gateway_version: 0.0.8

xroad_gateway:
  name: xroad-gateway
  user: xroad-gateway
  jar_url: https://github.com/educloudalliance/xroad-rest-gateway/releases/download/v{{ xroad_gateway_version }}/rest-gateway-{{ xroad_gateway_version }}.jar
  jar_checksum: sha256:702dd6e6681db6d795a999e0792d101d745b117f080e3acbec25c8052f5f02fb
  httpPort: "9090"
  httpsPort: "9091"
  propertiesDirectory: properties
  keystore_filename: "{{ xroad.securityserver.alias }}.jks"
  keyAlias: catalog
  securityserver_public_cert_filename: "{{ xroad.securityserver.alias }}.crt"
