---

- name: Download Solr package
  get_url: url={{ solr_download_url }} dest={{ cache_path }}/solr-{{ solr_version }}/solr.tgz mode=0644 owner=root group=root
  # creates solr.tgz

- name: Extract Solr installer from the archive
  # tar xzf solr-5.3.1.tgz solr-5.3.1/bin/install_solr_service.sh --strip-components=2
  unarchive: src={{ cache_path }}/solr-{{ solr_version }}/solr.tgz dest=/opt/solr copy=no
  # creates install_solr_service.sh

- name: Install Solr
  # sudo ./install_solr_service.sh solr-5.3.1.tgz -p 9900 -d basic_configs
  # sudo ./install_solr_service.sh solr-5.3.1.tgz -i /opt -d /var/solr -u solr -s solr -p 8983
  # chdir
  # user: solr
  # creates /opt/solr
  # ignore_errors: true (possibly not needed if using creates)

  # solr_url in ckan.ini should be http://localhost:9900/solr/ckancore

  # Create Solr core
  # /opt/solr-5.3.1/bin$ ./solr create -c ckancore -d basic_configs
  # chdir
  # user: solr
  # creates /var/solr/data/ckancore
  # ignore_errors: true (possibly not needed if using creates)
