---

- name: Ensure harvester cron job
  cron: name="harvest" minute="*/5" hour="0-3" job="{{ virtualenv }}/bin/paster --plugin=ckanext-harvest harvester run --config={{ ckan_ini }}"

- name: Ensure tracking cron job
  cron: name="tracking" minute="0" hour="0" job="{{ virtualenv }}/bin/paster --plugin=ckan tracking update --config={{ ckan_ini }} && {{ virtualenv }}/bin/paster --plugin=ckan search-index rebuild -r --config={{ ckan_ini }}"

- name: Ensure qa cron job
  cron: name="qa" minute="0" hour="6" job="{{ virtualenv }}/bin/paster --plugin=ckanext-qa qa update --config={{ ckan_ini }}"

- name: Ensure report cron job
  cron: name="report" minute="0" hour="7" job="{{ virtualenv }}/bin/paster --plugin=ckanext-report report generate --config={{ ckan_ini }}"
