---

- name: Create patch cache path
  file: path="{{ patches_cache_path }}" state=directory
  tags:
  - ckan
  - patch_ckan

- name: Fetch CKAN patches
  get_url: url="{{ item.patch }}" dest="{{ patches_cache_path }}/{{ item.file }}"
  register: fetch_patches
  with_items: ckan_patches
  tags:
  - ckan
  - patch_ckan

# fixGroupView is fixed in ckan 2.3 https://github.com/ckan/ckan/issues/1420
# downgradeSelect2js fixes ckan issue https://github.com/ckan/ckan/issues/1512
- name: Apply CKAN patches
  shell: patch -s -N -p1 < "{{ patches_cache_path }}/{{ item.file }}" chdir="{{ ckan_source_path }}"
  when: fetch_patches|changed
  ignore_errors: True
  with_items: ckan_patches
  tags:
  - ckan
  - patch_ckan
