- name: Create patch cache path
  file: path="{{ patches_cache_path }}" state=directory
  tags:
    - patch_ckan

- name: Copy CKAN patches
  copy: src="patches/{{ item.file }}.patch" dest="{{ patches_cache_path }}"
  with_items: "{{ ckan_patches }}"
  tags:
    - patch_ckan

- name: Remove existing files created by patches
  file: path={{ item.file }} state=absent
  with_items: "{{ files_created_by_patches }}"
  tags:
    - patch_ckan

- name: Apply CKAN patches
  shell: patch -s -N -p1 < "{{ patches_cache_path }}/{{ item.file }}.patch" chdir="{{ ckan_source_path }}"
  #ignore_errors: True
  with_items: "{{ ckan_patches }}"
  tags:
  - patch_ckan

- name: Re-minify CKAN core javascript files after patches
  shell: ./bin/paster --plugin=ckan minify {{ ckan_source_path }}/ckan/public/base/javascript "--config={{ ckan_ini }}" chdir="{{ virtualenv }}"
  tags:
  - patch_ckan
