---

- name: Install postgres
  apt: pkg={{ item }} state=latest
  with_items:
    - postgresql

- name: Copy postgres configurations
  template: src={{ item.file }} dest={{ item.dest }} owner=postgres group=postgres mode="0640"
  with_items:
  - { file: pg_hba.conf.j2, dest: /etc/postgresql/9.5/main/pg_hba.conf }
  - { file: postgresql.conf.j2, dest: /etc/postgresql/9.5/main/postgresql.conf }
  - { file: datastore_permissions.sql, dest: /tmp/datastore_permissions.sql }

- name: Generate self-signed SSL certificate
  command: openssl req -new -nodes -x509 -subj "/C=FI/ST=Helsinki/L=Helsinki/O=IT/CN={{ public_facing_hostname }}" -days 3650 -keyout "/var/lib/postgresql/9.5/main/server.key" -out "/var/lib/postgresql/9.5/main/server.crt" -extensions v3_ca creates="/var/lib/postgresql/9.5/main/server.crt"

- name: Set certificate file ownership and mode
  shell: chmod 600 /var/lib/postgresql/9.5/main/server.* && chown "postgres:postgres" /var/lib/postgresql/9.5/main/server.*

- name: Restart postgres
  service: name=postgresql state=restarted

- name: Setup postgres users
  become_user: postgres
  postgresql_user: user={{ item.value.username }} password={{ item.value.password }}
  with_dict: "{{ postgresql_users }}"

- name: Setup postgres databases
  become_user: postgres
  postgresql_db: name={{ item.value.name }} owner={{ item.value.owner }} encoding={{ item.value.encoding }} lc_collate={{ item.value.collate }} lc_ctype={{ item.value.ctype }} template={{ item.value.template }}
  with_dict: "{{ postgresql_databases }}"
  ignore_errors: True

- name: Setup datastore database permissions
  become_user: postgres
  shell: cat /tmp/datastore_permissions.sql | psql --set ON_ERROR_STOP=1