---

- name: Remove default styles (vagrant)
  file: path="/usr/lib/ckan/default/src/ckan/ckan/public/base/css" state=absent
  when: vagrant is defined
  tags:
    - style

- name: Link CSS files from host share (vagrant)
  file: src="/src/css" path="/usr/lib/ckan/default/src/ckan/ckan/public/base/css" state=link
  when: vagrant is defined
  tags:
    - style

- name: Copy CSS files (server deployment)
  copy: src="../css/" dest="/usr/lib/ckan/default/src/ckan/ckan/public/base/css/" owner=root group=root mode=0755
  when: vagrant is not defined
  tags:
    - style
