---

ckanext_sync_path: "{{ server_path }}"

ckan_extensions:
  - ckanext-sixodp_routes
  - ckanext-sixodp_scheming
  - ckanext-sixodp_ui
  - ckanext-scheming
  - ckanext-showcase
  - ckanext-fluent
  - ckanext-pages
  - ckanext-harvest
  - ckanext-cloudstorage
  - ckanext-report
  - ckanext-qa
  - ckanext-archiver
  - ckanext-hierarchy
  - ckanext-disqus
  - ckanext-reminder
  - ckanext-rating
  - ckanext-editor
  - ckanext-collection
  - ckanext-datasetcopy
  - ckanext-spatial
  - ckanext-datasubmitter
