---

# Warning! This file is open source and available in the Internet! Do not add
# any real secrets here! These are for local Vagrant and for reference.

secret:
  exposed_secrets: True
  database_piwik_password: "piwik"

