---

www_user: www-data
www_group: www-data

server_path: /opt/apicatalog
cache_path: "{{ server_path }}/cache"
data_path: "{{ server_path }}/data"

ckan_ini: /etc/ckan/default/production.ini
virtualenv: /usr/lib/ckan/default

certificates_path: /etc/ssl/apicatalog
