- name: re-minify ckanext-sixodp_ui module javascript files
  shell: ./bin/paster --plugin=ckan minify "{{ sixodp_ui_ckanext_path }}/fanstatic/javascript/modules" "--config={{ ckan_ini }}" chdir="{{ virtualenv }}"
  tags:
    - frontend-build

- name: rebuild ckanext-sixodp_ui less
  shell: lessc "{{ sixodp_ui_path }}/less/main.less" "{{ sixodp_ui_ckanext_path }}/fanstatic/main.css"
