---

- name: Ensure that gateway system user exists
  user: name={{ xroad_gateway.user }} createhome=no system=yes comment="{{ xroad_gateway.name }} system user"

- name: Ensure path exists
  file: path=/opt/{{ xroad_gateway.name }} state=directory mode=0755 owner={{ xroad_gateway.user }} group={{ xroad_gateway.user }}

- name: Download jar
  get_url:
    url: "{{ xroad_gateway.jar_url }}"
    checksum: "{{ xroad_gateway.jar_checksum }}"
    dest: /opt/{{ xroad_gateway.name }}/{{ xroad_gateway.name }}.jar
    owner: "{{ xroad_gateway.user }}"
    group: "{{ xroad_gateway.user }}"
    mode: "0600"

- name: Copy microservice config
  template: src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.owner }} mode={{ item.mode }}
  with_items:
    - {"src": "application.yml", "dest": "/opt/{{ xroad_gateway.name }}/application.yml", "owner": "{{ xroad_gateway.user }}", "mode": "0600"}
    - {"src": "initscript-upstart.conf", "dest": "/etc/init/{{ xroad_gateway.name }}.conf", "owner": "root", "mode": "0644"}

- name: Start the gateway
  service: name={{ xroad_gateway.name }} enabled=yes state=restarted
