---

- name: Ensure that gateway system user exists
  user: name={{ xroad_gateway.user }} createhome=no system=yes comment="{{ xroad_gateway.name }} system user"

- name: Ensure path exists
  file: path=/opt/{{ xroad_gateway.name }} state=directory mode="0700" owner={{ xroad_gateway.user }} group={{ xroad_gateway.user }}


- name: Create xroad-gateway config directory
  file: path=/opt/{{ xroad_gateway.name }}/{{ xroad_gateway.propertiesDirectory }} state=directory owner={{ xroad_gateway.user }} group={{ xroad_gateway.user }} mode="0700" recurse=yes

- name: Copy xroad-gateway config
  template: src={{ item }} dest="/opt/{{ xroad_gateway.name }}/{{ xroad_gateway.propertiesDirectory }}" owner={{ xroad_gateway.user }} group={{ xroad_gateway.user }} mode="0600"
  with_items:
    - "consumers.properties"
    - "consumer-gateway.properties"
    - "providers.properties"
    - "provider-gateway.properties"

- name: Copy gateway upstart configs
  template:
    src: initscript-upstart.conf
    dest: /etc/init/{{ xroad_gateway.name }}.conf
    owner: root
    group: root
    mode: "0644"

- name: Start the gateway
  service: name={{ xroad_gateway.name }} enabled=yes state=restarted
