---

- name: Reindex
  shell: touch "{{ files_root }}/.solr-reindex" && ./bin/paster --plugin=ckan search-index rebuild --config="{{ ckan_ini }}" chdir="{{ virtualenv }}" creates="{{ files_root }}/.solr-reindex"
  async: 1200
  poll: 0
