---

- name: Ensure Nginx is installed
  apt: pkg=nginx state=latest

- name: Copy Nginx sites and configuration files
  template:
    src: "{{ item.template }}"
    dest: "{{ item.destination }}"
    mode: "0644"
    owner: root
    group: root
  with_items:
    - { template: "nginx_site_config.j2", destination: "/etc/nginx/sites-available/primary_site" }
    - { template: "nginx.conf.j2", destination: "/etc/nginx/nginx.conf" }
    - { template: "php.conf", destination: "/etc/nginx/php.conf" }
  notify: Restart nginx

- name: Ensure static resource directory
  file: path="{{ static_path }}" state=directory mode="0775" owner=root group=root

- name: Copy static resource templates
  template: src={{ item.src }} dest={{ static_path }}/{{ item.dest }} mode="0644" owner=root group=root
  with_items:
    - { "src": "404.fi.html.j2", "dest": "404.fi.html" }
    - { "src": "404.sv.html.j2", "dest": "404.sv.html" }
    - { "src": "404.en.html.j2", "dest": "404.en_gb.html" }
    - { "src": "404.en.html.j2", "dest": "404.en_GB.html" }
    - { "src": "401.fi.html.j2", "dest": "401.fi.html" }
    - { "src": "401.sv.html.j2", "dest": "401.sv.html" }
    - { "src": "401.en.html.j2", "dest": "401.en_GB.html" }
    - { "src": "401.en.html.j2", "dest": "401.en_gb.html" }
    - { "src": "403.fi.html.j2", "dest": "403.fi.html" }
    - { "src": "403.sv.html.j2", "dest": "403.sv.html" }
    - { "src": "403.en.html.j2", "dest": "403.en_GB.html" }
    - { "src": "403.en.html.j2", "dest": "403_en_gb.html" }
    - { "src": "500.fi.html.j2", "dest": "500.fi.html" }
    - { "src": "500.sv.html.j2", "dest": "500.sv.html" }
    - { "src": "500.en.html.j2", "dest": "500.en_GB.html" }
    - { "src": "500.en.html.j2", "dest": "500.en_gb.html" }

- name: Ensure static file permissions
  command: chmod -R "0775" "{{ static_path }}"

- name: Copy Robots.txt
  template: src="robots.txt.j2" dest="{{ static_path }}/robots.txt" mode=0644 owner=www-data group=www-data

- name: Synchronize asset directory
  synchronize: src="{{ playbook_dir }}/../shared/assets/" dest="{{ assets_path }}/"
  when: deployment_environment_id != "vagrant"

- name: Symlink asset directory from host machine (Vagrant)
  file: src="/vagrant/shared/assets" path="{{ assets_path }}" state=link
  when: deployment_environment_id == "vagrant"

- name: Disable default site
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Enable Nginx site
  file: src="/etc/nginx/sites-available/{{ item }}" dest="/etc/nginx/sites-enabled/{{ item }}" state=link
  with_items:
    - primary_site
  notify: Restart nginx

- include_tasks: ssl.yml
  when: nginx.use_ssl_certificate


