---

- name: Ensure SSL certificate directory
  file: path="{{ ssl_certificate_path }}" state=directory mode="0700" owner=root group=root

- include: ssl_self-signed.yml
  when: nginx.use_selfsigned_certificate|bool

- block:
  - name: Symlink chain certificate
    file:
      src: "/etc/letsencrypt/live/{{ public_facing_hostname }}/fullchain.pem"
      dest: "{{ ssl_certificate_path }}/{{ ssl_cert_filename }}"
      state: link

  - name: Symlink certificate key
    file:
      src: "/etc/letsencrypt/live/{{ public_facing_hostname }}/privkey.pem"
      dest: "{{ ssl_certificate_path }}/{{ ssl_key_filename }}"
      state: link
  when: not nginx.use_selfsigned_certificate|bool

- name: Copy strong Diffie-Hellman key exchange parameters
  copy: src=dhparams.pem dest="{{ ssl_dh_parameters_path }}"

- name: Ensure certificate file permissions
  file: path="{{ ssl_certificate_path }}" state=directory mode="0600" recurse=yes owner=root group=root follow=no
