---

- name: Ensure SSL certificate directory
  file: path="{{ ssl_certificate_path }}" state=directory mode="0700" owner=root group=root

- include: ssl_self-signed.yml
  when: nginx.use_selfsigned_certificate

- name: Generate strong Diffie-Hellman key exchange parameters
  command: "openssl dhparam -out {{ ssl_dh_parameters_path }} 2048 creates={{ ssl_dh_parameters_path }}"

- name: Ensure certificate file permissions
  file: path="{{ ssl_certificate_path }}" state=directory mode="0600" recurse=yes owner=root group=root
