---

- name: Create backup directory
  file: path={{ item }} state=directory
  with_items:
  - "{{ backup_path }}"
  - "{{ backup_scripts_path }}"

- name: Setup database backup
  template: src=autopostgresqlbackup.j2 dest=/etc/default/autopostgresqlbackup mode="0755" owner=root group=root

- name: Copy backup cleanup
  template: src=clean_backups.sh.j2 dest=/etc/cron.daily/clean_postgre_backups mode="0755" owner=root group=root

 # pg_dumpall | gzip > dumppi.gz
