---

# To run:
# ansible-playbook -v -i inventories/vagrant deploy-all.yml
# ansible-playbook -v -i inventories/demo deploy-all.yml

- hosts: mainserver
  become: true
  vars_files:
    - "vars/common.yml"
    - "vars/environment-specific/{{ deployment_environment_id }}.yml"
    - "{{ secrets_file_path }}"
  roles:
    - wordpress
