---

# To run:
# ansible-playbook -v -i inventories/vagrant deploy-extensions.yml
# ansible-playbook -v -i inventories/demo deploy-extensions.yml

- hosts: mainserver
  become: true
  vars_files:
    - "vars/common.yml"
    - "vars/environment-specific/{{ deployment_environment_id }}.yml"
    - "{{ secrets_file_path }}"
  roles:
    - ckan-extensions
    - ckan-config
    - ckan-translations
    - ckan-restart
