---

# This playbook is used to install the service on a transitional cloudformation
# infrastructure until the rest of the components are dockerized

- hosts: mainserver
  connection: local
  become: true
  vars_files:
    - "vars/common.yml"
    - "vars/environment-specific/{{ deployment_environment_id }}.yml"
    - "{{ secrets_file_path }}"
  roles:
    - os-base
    - java8
    - nodejs
    #- ssh # Done in cloudformation bootstrapping
    - postgres-install
    #- postgres-backup # Replaced by RDS
    - postgres-data
    - solr6
    - redis
    - nginx
    - role: geerlingguy.certbot
      when: deployment_environment_id != "vagrant" and deployment_environment_id != "build"
    - apache
    - postfix
    - ckan-extensions
    - ckan-install
    - ckan-config
    - ckan-install-patches
    - ckan-database
    - ckan-cron
    - datapusher
    #- transifex-install Only used on Vagrant
    - ckan-translations
    - ckan-restart
    - supervisor
    - solr-reindex
    - php-fpm
    - mysql
    - wordpress
    - phppgadmin
