---

# To run:
# ansible-playbook -v -i inventories/vagrant deploy-extensions.yml
# ansible-playbook --ask-vault-pass -v -i inventories/qa deploy-extensions.yml

- hosts: mainserver
  become: true
  vars_files:
    - "vars/common.yml"
    - "vars/environment-specific/{{ deployment_environment_id }}.yml"
    - "{{ secrets_file_path }}"
  roles:
    - { role: ckan-extension, ckanext: ckanext-sixodp_routes }
    - { role: ckan-extension, ckanext: ckanext-apicatalog_scheming }
    - { role: ckan-extension, ckanext: ckanext-apicatalog_ui }
    - { role: ckan-extension, ckanext: ckanext-fluentall }
    - { role: ckan-extension, ckanext: ckanext-scheming }
    - { role: ckan-extension, ckanext: ckanext-fluent }
    - { role: ckan-extension, ckanext: ckanext-pages }
    - { role: ckan-extension, ckanext: ckanext-contact }
    - { role: ckan-extension, ckanext: ckanext-harvest }
    - ckan
    - ckan-translations
  handlers:
    - include: handlers/handlers.yml
