---

# To run:
# ansible-playbook -v -i inventories/vagrant deploy-all.yml
# ansible-playbook --ask-vault-pass -v -i inventories/beta deploy-all.yml

- hosts: mainserver
  sudo: true
  vars_files:
    - "vars/common.yml"
    - "vars/environment-specific/{{ deployment_environment_id }}.yml"
    - "{{ secrets_file_path }}"
  roles:
    - os-base
    - ssh
    - postgre
    - solr3
    - redis
    - nginx
    - apache
    - { role: ckan-extension, ckanext: ckanext-apicatalog_scheming }
    - { role: ckan-extension, ckanext: ckanext-apicatalog_ui }
    - { role: ckan-extension, ckanext: ckanext-fluentall }
    - ckan
    - ckan-translations
    - solr-reindex
  handlers:
    - include: handlers/handlers.yml
