---

# To run:
# ansible-playbook -v -i inventories/vagrant deploy-all.yml
# ansible-playbook -v -i inventories/demo deploy-all.yml

- hosts: mainserver
  become: true
  vars_files:
    - "vars/common.yml"
    - "vars/environment-specific/{{ deployment_environment_id }}.yml"
    - "{{ secrets_file_path }}"
  roles:
    - os-base
    - java
    - nodejs
    - ssh
    - postgres-install
    - postgres-backup
    - postgres-data
    - solr
    - redis
    - apache
    - postfix
    - ckan-extensions
    - ckan-install
    - ckan-config
    - ckan-install-patches
    - ckan-database
    - ckan-cron
    - datapusher
    - supervisor
    - nginx
    - transifex-install
    - ckan-translations
    - ckan-restart
    - solr-reindex
    - php-fpm
    - mysql
    - wordpress
    - phppgadmin

