---

# To run:
# ansible-playbook -v -i inventories/vagrant deploy-all.yml
# ansible-playbook --ask-vault-pass -v -i inventories/qa deploy-all.yml

- hosts: mainserver
  become: true
  vars_files:
    - "vars/common.yml"
    - "vars/environment-specific/{{ deployment_environment_id }}.yml"
    - "{{ secrets_file_path }}"
  roles:
    - os-base
    - java8
    - ssh
    - postgres
    - postgres-backup
    - solr6
    - redis
    - nginx
    - apache
    - postfix
    - node
    - { role: ckan-extension, ckanext: ckanext-sixodp_routes }
    - { role: ckan-extension, ckanext: ckanext-sixodp_scheming }
    - { role: ckan-extension, ckanext: ckanext-sixodp_ui }
    - { role: ckan-extension, ckanext: ckanext-fluentall }
    - { role: ckan-extension, ckanext: ckanext-scheming }
    - { role: ckan-extension, ckanext: ckanext-fluent }
    - { role: ckan-extension, ckanext: ckanext-pages }
    - { role: ckan-extension, ckanext: ckanext-contact }
    - { role: ckan-extension, ckanext: ckanext-harvest }
    - ckan
    #- ckan-translations
    #- supervisor
    - solr-reindex
  handlers:
    - include: handlers/handlers.yml
