---

# Frontend build playbook for development
# To run:
# ansible-playbook -v -i inventories/vagrant frontend-build.yml

- hosts: mainserver
  become: true
  vars_files:
    - "vars/common.yml"
    - "vars/environment-specific/{{ deployment_environment_id }}.yml"
    - "{{ secrets_file_path }}"
  roles:
    #- ckan-ui
    - { role: ckan-extensions, ckan_extensions: ckanext-sixodp }
    - ckan
    - ckan-translations
    - ckan-restart
