---

- name: Remove existing files created by patches
  file: path={{ item.file }} state=absent
  with_items: "{{ files_created_by_patches }}"
  tags:
    - patch_ckan

- name: Apply CKAN patches
  patch:
    src: patches/{{ item.file }}.patch
    basedir: "{{ ckan_source_path }}"
    strip: 1
  with_items: "{{ ckan_patches }}"
  tags:
  - patch_ckan

- name: Re-minify CKAN core javascript files after patches
  shell: ./bin/paster --plugin=ckan minify {{ ckan_source_path }}/ckan/public/base/javascript "--config={{ ckan_ini }}" chdir="{{ virtualenv }}"
  tags:
  - patch_ckan

- name: Re-minify CKAN vendor javascript files after patches
  shell: ./bin/paster --plugin=ckan minify {{ ckan_source_path }}/ckan/public/base/vendor "--config={{ ckan_ini }}" chdir="{{ virtualenv }}"
  tags:
    - patch_ckan