---

- name: Remove existing files created by patches
  file: path={{ item.file }} state=absent
  with_items: "{{ files_created_by_patches }}"
  when: files_created_by_patches is defined
  tags:
    - patch_ckan

- name: Apply CKAN patches
  patch:
    src: patches/{{ item.file }}.patch
    basedir: "{{ ckan_source_path }}"
    strip: 1
  with_items: "{{ ckan_patches }}"
  tags:
  - patch_ckan
