---

ckan_package: python-ckan_{{ ckan_version }}_amd64.deb

harvester_user: "{{ www_user }}"
celery_user: "{{ www_user }}"

# plugin order matters, when templates call super()
ckan_plugins: stats scheming_datasets fluent

#ckan_extensions:
#  - ckanext-ytp-tasks
#  - ckanext-ytp-request
#  - ckanext-ytp-main
#  - ckanext-googleanalytics
#  - ckanext-ytp-comments
#  - "ckanext-qa"
#  - "ckanext-datarequests"
#  - "ckanext-harvest"
#  - "ckanext-archiver"
#  - "ckanext-spatial"
#  - "ckanext-report"

redis_harvest_database: 0
redis_celery_database: 1

supervisor_services:
  - ckan_gather_consumer
  - ckan_fetch_consumer
  - celery_celery
  - celery_bulk
  - celery_priority
  - celerybeat

# Override these on servers! 
baker_session_secret: "9PBdkhaxLGWW4M4jeTI25h+4t"
app_instance_uuid: "{dc6259b8-f112-4d23-8816-aadabba1985c}"

ckan_files_path: "{{ files_root }}/ckan"
ckan_max_resource_size: 50
translation_cache_path: "{{ cache_path }}/translations"
translation_languages:
  - "fi"
  - "sv"

translation_projects:
  - "ckanext-ytp-request"
  - "ytp-assets-common"
  - "ckanext-ytp-main"
  - "ckanext-ytp-comments"
  - "ckanext-qa"
  - "ckanext-datarequests"

ckan_site_id: "default"

patches_cache_path: "{{ cache_path }}/patch"
ckan_source_path: "{{ virtualenv }}/src/ckan"
spatial_source_path: "{{ virtualenv }}/src/ckanext-spatial"

ckan_patches:
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/e7936fe8707a847387661248b5b0d9d3ddc526ae.patch", file: "fix_hardcoded_languages.patch" } # ytp specific
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/4d596cca05a55fdcba9fbc2af1ecaf46b843b737.patch", file: "fix_invalid_date_indexing.patch" } # ytp specific
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/7367b56bc023da854aa31e05ff63ef8307c06f41.patch", file: "fix_multilingual_search.patch" } # ytp specific
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/9e80b58f24dea9d93ec84aac258f5436dfcfdd9c.patch", file: "fix_collection_type_translation.patch" } # ytp specific
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/5b7a63d86291987646ff5275c068f41eab21b128.patch", file: "fix_autocomplete_input_delay.patch" } # ytp specific
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/cbbca2047c68c377ef9408fc4df157b1acb1b02c.patch", file: "usability-fix-for-image-upload.patch" } # ytp specific
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/8f7ec3f9fb6a35bb4a7e52784920ed99b7c7e245.patch", file: "fix-double-encoding-in-autocomplete.patch"} # ytp specific
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/cde3c21a8b8612b88ef61b47488465b2926a6840.patch", file: "fix-template-error-in-resources.patch"} # ytp specific
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/eb59ffde3a702077ffbc8de8e3ff425b29974d6c.patch", file: "add-event-callbacks-to-autocomplete.patch"} # ytp specific
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/9497130896c969982a3b8b5e9685295428fd7d2b.patch", file: "enable-url-quoting"} # pullreq in ckan master
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/85ef19c73faa7e841e9e0b94ec1044dbb6fee389.patch", file: "enable-celery-queues"} # ytp specific

service_database_enabled: false
auto_author_enabled: true
