---

ckan_version: 2.5.2

harvester_user: "{{ www_user }}"
celery_user: "{{ www_user }}"

# plugin order matters, when templates call super()
ckan_plugins: pages text_view apicatalog_scheming scheming_datasets fluent apicatalog_ui fluentall_pkg fluentall_res apicatalog_routes contact apicatalog_feed harvest xroad_harvester wsdl_view

redis_harvest_database: 0
redis_celery_database: 1

ckan_storage_path: "{{ data_path }}/ckan"
ckan_max_resource_size: 50

ckan_site_id: "default"

patches_cache_path: "{{ cache_path }}/patch"
ckan_source_path: "{{ virtualenv }}/src/ckan"

service_database_enabled: false
auto_author_enabled: true

ckan_patches:
  - { file: "fix_401_to_403" }
  - { file: "remove_gravatar" }
  - { file: "csrf" }
  - { file: "alert_fix" }
  - { file: "fix_unmodified_package_validation" }

files_created_by_patches:
  - { file: '/usr/lib/ckan/default/src/ckan/ckan/lib/csrf_token.py'}

search_engine_robots_filename: robots_disallowed.txt