---

harvester_user: "{{ www_user }}"
celery_user: "{{ www_user }}"

# plugin order matters, when templates call super()
ckan_plugins: stats scheming_datasets fluent apicatalog_ui apicatalog_scheming

redis_harvest_database: 0
redis_celery_database: 1

supervisor_services:
  - ckan_gather_consumer
  - ckan_fetch_consumer
  - celery_celery
  - celery_bulk
  - celery_priority
  - celerybeat

# Override these on servers! 
baker_session_secret: "9PBdkhaxLGWW4M4jeTI25h+4t"
app_instance_uuid: "{dc6259b8-f112-4d23-8816-aadabba1985c}"

ckan_files_path: "{{ files_root }}/ckan"
ckan_max_resource_size: 50

ckan_site_id: "default"

patches_cache_path: "{{ cache_path }}/patch"
ckan_source_path: "{{ virtualenv }}/src/ckan"

service_database_enabled: false
auto_author_enabled: true
