---

- name: Disable emails in cron
  cronvar: name="MAILTO" value="\"\""

# Check new harvester jobs every hour, does not execute harvesting if there are no new jobs
- name: Ensure harvester cronjob
  cron: name="Harvester run" minute="0" job="/usr/lib/ckan/default/bin/paster --plugin=ckanext-harvest harvester run --config={{ ckan_ini }}"
