---

- name: Disable emails in cron
  cronvar: name="MAILTO" value="\"\""

# Check new harvester jobs every hour, does not execute harvesting if there are no new jobs
- name: Ensure harvester cronjob
  cron: name="Harvester run" minute="0" job="/usr/lib/ckan/default/bin/paster --plugin=ckanext-harvest harvester run --config={{ ckan_ini }}"
  when: "'ckanext-harvest' in ckan_extensions"

- name: Disable qa update
  cron: name="QA update" state=absent

- name: Disable qa update
  cron: name="Qa run" state=absent

- name: Ensure reminder cronjob
  cron: name="Reminder send" minute="0" hour="7" job="/usr/lib/ckan/default/bin/paster --plugin=ckanext-reminder reminder send --config={{ckan_ini}}"

- name: Ensure reminder notify subscribers cronjob
  cron: name="Reminder run" minute="0" hour="8" job="/usr/lib/ckan/default/bin/paster --plugin=ckanext-reminder reminder notify --config={{ckan_ini}}"

- name: Ensure CKAN tracking
  cron: name="CKAN tracking" minute="0" hour="0" job="/usr/lib/ckan/default/bin/paster --plugin=ckan tracking update --config={{ckan_ini}} && /usr/lib/ckan/default/bin/paster --plugin=ckan search-index rebuild -r --config={{ckan_ini}}"

- name: Ensure googleanalytics loadanalytics cronjob
  cron: name="Load Google Analytics" minute="0" hour="1" job="/usr/lib/ckan/default/bin/paster --plugin=ckanext-googleanalytics loadanalytics {{ google_analytics_secrets_file_path }} --config={{ ckan_ini }}"
  when: "'ckanext-googleanalytics' in ckan_extensions"

- name: Ensure archiver update
  cron: name="Archiver update" minute="0" hour="2" job="/usr/lib/ckan/default/bin/paster --plugin=ckanext-archiver archiver update --config={{ ckan_ini }}"
  when: "'ckanext-archiver' in ckan_extensions"