---

- name: Disable emails in cron
  cronvar: name="MAILTO" value="\"\""

# Check new harvester jobs every hour, does not execute harvesting if there are no new jobs
- name: Ensure harvester cronjob
  cron: name="Harvester run" minute="0" job="/usr/lib/ckan/default/bin/paster --plugin=ckanext-harvest harvester run --config={{ ckan_ini }}"

- name: Ensure qa cronjob
  cron: name="Qa run" minute="0" hour="0" job="/usr/lib/ckan/default/bin/paster --plugin=ckanext-qa qa update --config={{ ckan_ini }}"

- name: Ensure reminder cronjob
  cron: name="Reminder run" minute="0" hour="7" job="/usr/lib/ckan/default/bin/paster --plugin=ckanext-reminder reminder send --config={{ckan_ini}}"

- name: Ensure reminder nofity subscribers cronjob
  cron: name="Reminder run" minute="0" hour="8" job="/usr/lib/ckan/default/bin/paster --plugin=ckanext-reminder reminder notify --config={{ckan_ini}}"