---

- name: Ensure CKAN directory structure for test configs
  file: path={{ item }} state=directory
  with_items:
    - "/src/ckanext/ckan"
    - "{{ server_path }}/ckan"

- name: Copy CKAN configuration
  template: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }} owner={{ item.owner }} group={{ item.group }}
  with_items:
    - { src: ckan.py, dest: /usr/bin/ckan, mode: "0755", owner: root, group: root }
    - { src: ckan.ini.j2, dest: "{{ ckan_ini }}", mode: "0640", owner: "{{ www_user }}", group: "{{ www_group }}" }
    - { src: wsgi.py.j2, dest: /etc/ckan/default/wsgi.py, mode: "0640", owner: "{{ www_user }}", group: "{{ www_group }}" }
    - { src: test-core.ini.j2, dest: "/src/ckanext/ckan/test-core.ini", mode: "0644", owner: root, group: "{{ www_group }}"}
    - { src: test-core.ini.j2, dest: "{{ ckan_test_core_ini }}", mode: "0644", owner: root, group: "{{ www_group }}"}
    - { src: who.ini.j2, dest: "/src/ckanext/ckan/who.ini", mode: "0644", owner: root, group: "{{ www_group }}"}
    - { src: who.ini.j2, dest: "{{ ckan_who_ini }}", mode: "0644", owner: root, group: "{{ www_group }}"}
    - { src: test.ini.j2, dest: "/src/ckanext/ckan/test.ini", mode: "0644", owner: root, group: "{{ www_group }}"}
